### ISSUE TITLE
Minimal Testing

### ISSUE THREAD

**Issue by mondus** [m2lines/equation_discovery#3]
The original https://github.com/m2lines/pyqg_parameterization_benchmarks repo does not contain unit tests for the equation discovery module.

A minimal test could be defined to simply import the refactored module and ensure no errors occur. 

A secondary functional test could be created by considering the [Hybrid Symbolic](https://github.com/m2lines/pyqg_parameterization_benchmarks/blob/master/notebooks/hybrid_symbolic.ipynb) notebook and using a statistical check to ensure that given the example input used in the notebook an expected value is produced. This would require codifying the check against the visual outputs that are produced in the notebook example.

Addition of some minimal testing would allow the development of more advanced unit tests at a later date and would ensure that a minimal set of tests exists to build a CI pipeline. Eg. #1

**Comment by jdenholm** [comment]
There is a minimal import test in ``dev`` now.
